name: Release API

on:
  push:
    branches: [staging, prod]

env:
  CURRENT_SERVICE: ${{ github.event.repository.name }}-api
  AWS_ECR_URI: 604313529175.dkr.ecr.ap-southeast-1.amazonaws.com
  NAMESPACE: ${{ github.ref_name }}
  ZONE: ap-southeast-1
  CLUSTER_NAME: fewcha_remake
  AWS_ACCOUNT_ID: 604313529175

jobs:
  build_and_publish:
    name: Build And Publish
    runs-on: ubuntu-latest
    steps:
      - name: Run a script in a api directory
        run: |
          echo "Running in the api directory"
          ls
        working-directory: ./api

      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.ZONE }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Release Build
        run: cargo build --release

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Service docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: k8s/Dockerfile
          push: true
          tags: ${{ env.AWS_ECR_URI }}/${{ env.CURRENT_SERVICE }}:${{ env.NAMESPACE }}
          cache-from: type=registry,ref=${{ env.AWS_ECR_URI }}/${{ env.CURRENT_SERVICE }}:${{ env.NAMESPACE }}
          cache-to: type=inline

  rollout:
    name: Rollout Service
    runs-on: ubuntu-latest
    needs: build_and_publish
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.ZONE }}

      - name: Config K8s credentials
        run: |-
          aws eks --region ${{ env.ZONE }} update-kubeconfig --name ${{ env.CLUSTER_NAME }}

      - name: Apply to K8S
        run: |-
          kubectl rollout restart -n utxo-global-${{ env.NAMESPACE }} deploy ${{ env.CURRENT_SERVICE }}
